language: objective-c
osx_image: xcode611

before_install:
    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
    - cd ios/Library
    - pod install
    - ./run-tests.sh
    - cd ../..
